### PR TITLE
Provided Vars to more than "code" code blocks, fixed remarking code logic

### PR DESCRIPTION
**Pull request by ninaTorgunakova**
Solves https://github.com/gravitational/docs/issues/186.
The problem that invoked bug https://github.com/gravitational/teleport/pull/26636 was in the function `remarkCodeSnippet`: if a line wasn't connected to commands, and it wasn't a comment, it still defined as `CommandComment`, which hasn't got logic to detect Vars inside. So inside the `code` block but after the `CommandLine` variables weren't recognized.
I fixed the logic inside the last `else` in the condition: now `CommandComment` is a line that related to commands and that begins with grate as intended; all other lines that are not commands, vars, comments, etc are the `CodeLine`, and they support `Vars` inside like commands.
To cover the case that invoked the bug, I added a new uvu-test.

The next thing that was done is provide Vars supporting not only in `code` code blocks. To do it, I added the list of languages in MDX syntax that should support code snippet remarking. It includes languages and formats which are used in the content (let me know if some language from this list seems useless to you for this feature, and it can be removed from the list altogether).
Also, added the test to cover the correctness of support for new MDX languages in this list (yaml is taken as an example).

Also, added a few minor visual changes:
- Made font-size of Vars slightly smaller (based on the comment https://github.com/gravitational/docs/issues/186#issuecomment-1570148841);
- Made color of the font inside snippet-wrapper 20% lighter because I noticed places where there was a pretty low contrast with black snippet background.

After merging this PR, Vars in the code output on the Register Cluster page can be successfully returned (that were removed in this PR https://github.com/gravitational/teleport/pull/26636):
fix
Last thing to consider is the most part of code-highlighting is not supported along with variable syntax, it requires a lot of time to support these features together. When we discussed the scope of tasks with Sasha Klizhentas, I warned about that, and he agreed that preserving highlighting here wouldn't be too important.
So the appearance of yaml code block will be like this:
yaml

### CODE REVIEW

**Review by avatus — APPROVED** [review]

**Comment by avatus** [comment]
@ninaTorgunakova are you able to merge once approvals are received or do you lack those permissions as well? Just wondering if I'll need to merge or if you can.

**Comment by ninaTorgunakova** [comment]
@avatus No, I still don't receive enough permissions to merge pull requests or assign reviewers :( Can I ask you to do it, please? I'll remind about permissions once more soon

**Review by alexfornuto — APPROVED** [review]
Reviewing purely from an end user perspective (ie no input on the code itself), it seems to work as requested. Thanks!

**Comment by avatus** [comment]
> Last thing to consider is the most part of code-highlighting is not supported along with variable syntax, it requires a lot of time to support these features together. When we discussed the scope of tasks with Sasha Klizhentas, I warned about that, and he agreed that preserving highlighting here wouldn't be too important.

The yaml breaking was noted and seems to be ok'd from a product perspective.

**Comment by alexfornuto** [comment]
That was my mistake, I didn't read that section carefully enough. I disagree, syntax highlighting is very important, and shouldn't be sacrificed to expand Var usage. I'll put up a revert PR.

**Comment by ptgott** [comment]
@ninaTorgunakova After talking about this, we want to go for a middle-of-the-road solution to the issue of allowing `Var`s in non-`code` blocks versus enabling syntax highlighting.

We would make the new `Var` behavior opt-in, so you would enable it by including a code fence like this:

````
```var
This is a code fence that allows for <Var name="myvar" />
```
````

`code` snippets would still allow `Var`s (just like before), but non-`var` snippets would not. `var` snippets would behave as `text` snippets (i.e., without syntax highlighting), but would enable `Var`s.

What do you think?

**Comment by ninaTorgunakova** [comment]
@ptgott @alexfornuto That sounds like a good compromise! If that syntax will be convenient for you to use in the future, let's choose this approach without losing highlighting.
Is it better to describe this solution somewhere besides the issue?

**Pull request merged**
