### PR TITLE
Add mermaid charts support

### PR DESCRIPTION
**Pull request by iAdramelk**
Add support for mermaid graphs.

To test, add mermaid chat to the mdx file. E. g.:

````
```mermaid
graph LR
    Start --> Stop
```
````

Upd:

Default plugin didn't have all the options we needed, so I rewrote it to add them:

- `configFilePath` for theme support. Put theme variables here to change colors.
- `destinationDir` and `staticPath` will be needed after merging the #225 to cache images between builds correctly.

### CODE REVIEW

**Review by avatus — DISMISSED** [review]

**Comment by alexfornuto** [comment]
I tested as suggested. It looks like the module being imported is out of date. It will handle `graph` type graphs, but others like `flowchart` result in errors:

```
wait  - compiling /ver/11.x/installation (client and server)...
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Evaluation failed: Error: Parse error on line 1:
flowchart LR  C(End
^
Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
    at Yt.parseError (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:486512)
    at Yt.parse (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:487678)
    at Object.e.getClasses (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:749437)
    at Object.render (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:759998)
    at s (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:8:233)
    at Object.init (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:8:318)
    at __puppeteer_evaluation_script__:17:20
    at ExecutionContext._evaluateInternal (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async ElementHandle.evaluate (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:55:12)
    at async ElementHandle.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:478:20)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:111:15)
    at ElementHandle.evaluate (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:55:42)
    at ElementHandle.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:112:23)
    at ElementHandle.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:478:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  -- ASYNC --
    at ElementHandle.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/DOMWorld.js:156:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/Page.js:347:29)
    at Page.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/index.bundle.js:83:14
    at Generator.next (<anonymous>)
    at step (/Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/index.bundle.js:4:191)
    at /Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/index.bundle.js:4:361
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.4.0
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Evaluation failed: Error: Parse error on line 1:
flowchart LR  C(End
^
Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
    at Yt.parseError (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:486512)
    at Yt.parse (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:487678)
    at Object.e.getClasses (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:749437)
    at Object.render (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:759998)
    at s (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:8:233)
    at Object.init (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:8:318)
    at __puppeteer_evaluation_script__:17:20
    at ExecutionContext._evaluateInternal (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async ElementHandle.evaluate (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:55:12)
    at async ElementHandle.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:478:20)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:111:15)
    at ElementHandle.evaluate (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:55:42)
    at ElementHandle.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:112:23)
    at ElementHandle.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:478:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  -- ASYNC --
    at ElementHandle.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/DOMWorld.js:156:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/Page.js:347:29)
    at Page.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/index.bundle.js:83:14
    at Generator.next (<anonymous>)
    at step (/Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/index.bundle.js:4:191)
    at /Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/index.bundle.js:4:361
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.4.0
error - ./content/11.x/docs/pages/installation.mdx
Error: installation.mdx:Error: Unknown language: `mermaid` is not registered
info  - automatically enabled Fast Refresh for 1 custom loader
wait  - compiling /_error (client and server)...
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Evaluation failed: Error: Parse error on line 1:
flowchart LR  C(End
^
Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
    at Yt.parseError (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:486512)
    at Yt.parse (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:487678)
    at Object.e.getClasses (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:749437)
    at Object.render (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:759998)
    at s (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:8:233)
    at Object.init (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:8:318)
    at __puppeteer_evaluation_script__:17:20
    at ExecutionContext._evaluateInternal (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async ElementHandle.evaluate (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:55:12)
    at async ElementHandle.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:478:20)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:111:15)
    at ElementHandle.evaluate (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:55:42)
    at ElementHandle.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:112:23)
    at ElementHandle.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:478:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  -- ASYNC --
    at ElementHandle.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/DOMWorld.js:156:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/Page.js:347:29)
    at Page.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/index.bundle.js:83:14
    at Generator.next (<anonymous>)
    at step (/Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/index.bundle.js:4:191)
    at /Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/index.bundle.js:4:361
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.4.0
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Evaluation failed: Error: Parse error on line 1:
flowchart LR  C(End
^
Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
    at Yt.parseError (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:486512)
    at Yt.parse (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:487678)
    at Object.e.getClasses (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:749437)
    at Object.render (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:1:759998)
    at s (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:8:233)
    at Object.init (file:///Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/mermaid.min.js:8:318)
    at __puppeteer_evaluation_script__:17:20
    at ExecutionContext._evaluateInternal (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async ElementHandle.evaluate (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:55:12)
    at async ElementHandle.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:478:20)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:111:15)
    at ElementHandle.evaluate (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:55:42)
    at ElementHandle.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:112:23)
    at ElementHandle.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/JSHandle.js:478:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  -- ASYNC --
    at ElementHandle.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/DOMWorld.js:156:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.$eval (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/Page.js:347:29)
    at Page.<anonymous> (/Users/alex/projects/gravitational/docs/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/index.bundle.js:83:14
    at Generator.next (<anonymous>)
    at step (/Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/index.bundle.js:4:191)
    at /Users/alex/projects/gravitational/docs/node_modules/mermaid.cli/index.bundle.js:4:361
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.4.0
error - ./content/11.x/docs/pages/installation.mdx
Error: installation.mdx:Error: Unknown language: `mermaid` is not registered
```

**Comment by ptgott** [comment]
It looks like `remark-mermaid` depends on a very old version of `mermaid.cli`, which is now a different package (https://www.npmjs.com/package/@mermaid-js/mermaid-cli). Should we vendor the package and update the dependency?

**Comment by iAdramelk** [comment]
Ok, let me check it tomorrow. There are like 10 different versions of remark mermaid plugins. I will try some other ones, and if none of them works as intended, I will just copy it to the repo and manually adjust for our needs. They are all around 100loc.

**Comment by iAdramelk** [comment]
Replacing `mermaid.cli` with `@mermaid-js/mermaid-cli` fixed the problem. Please try it again.

**Comment by alexfornuto** [comment]
With this chart:

````
```mermaid
flowchart LR
  C(End User)
  D(Identity Provider)
  C==o A
  A-.-D
  subgraph lan[Internal Network]
    style lan stroke-dasharray: 5 5
    A(Teleport)
    B(Upstream Service)
    A --- B
  end
```
````

The dev server builds the page with the chart (but takes quite awhile), but the terminal is not happy about it:

```
event - compiled client and server successfully in 17.4s (1069 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
Error: Aborted because ./content/11.x/docs/pages/index.mdx is not accepted
Update propagation: ./content/11.x/docs/pages/index.mdx -> ./node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js?absolutePagePath=%2FUsers%2Falex%2Fprojects%2Fgravitational%2Fdocs%2Fpages%2Fver%2F11.x%2Findex.mdx&page=%2Fver%2F11.x!
    at applyHandler (http://localhost:3000/docs/_next/static/chunks/webpack.js?ts=1674668005390:869:31)
    at http://localhost:3000/docs/_next/static/chunks/webpack.js?ts=1674668005390:552:21
    at Array.map (<anonymous>)
wait  - compiling...
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
Error: Aborted because ./content/11.x/docs/pages/index.mdx is not accepted
Update propagation: ./content/11.x/docs/pages/index.mdx -> ./node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js?absolutePagePath=%2FUsers%2Falex%2Fprojects%2Fgravitational%2Fdocs%2Fpages%2Fver%2F11.x%2Findex.mdx&page=%2Fver%2F11.x!
    at applyHandler (http://localhost:3000/docs/_next/static/chunks/webpack.js?ts=1674668038282:869:31)
    at http://localhost:3000/docs/_next/static/chunks/webpack.js?ts=1674668038282:552:21
    at Array.map (<anonymous>)
event - compiled client and server successfully in 2.4s (1069 modules)
```

**Comment by iAdramelk** [comment]
Thank you. Let me check it.

**Comment by iAdramelk** [comment]
Ok, I updated this PR with my own version of the mermaid plugin because non of the existing ones worked as I needed. Added theme support and some variables that will be needed after #225 merge. For me, it does not throw any errors not at build time, not in the browser console, but please test it.

**Comment by alexfornuto** [comment]
1. The mermaid charts are working. I'm still getting these errors on refresh, though I'm not sure they're related:

```
Error: Aborted because ./content/11.x/docs/pages/index.mdx is not accepted
Update propagation: ./content/11.x/docs/pages/index.mdx -> ./node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js?absolutePagePath=%2FUsers%2Falex%2Fprojects%2Fgravitational%2Fdocs%2Fpages%2Fver%2F11.x%2Findex.mdx&page=%2Fver%2F11.x!
    at applyHandler (http://localhost:3000/docs/_next/static/chunks/webpack.js?ts=1674851275871:869:31)
    at http://localhost:3000/docs/_next/static/chunks/webpack.js?ts=1674851275871:552:21
    at Array.map (<anonymous>)
```

2. Can we make the adjustments required to make it [accept images](https://github.com/mermaid-js/mermaid/issues/1133)?

3. It looks new files, both `svg` and `mmd` are created on every refresh.

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        docs/pages/341ee9545a206e2332467a232fb0d7c049f14a7f.svg
        docs/pages/35cfbb05331c61282bef7756f0d6cdfd9069dcb2.mmd
        docs/pages/5955eae845992db594a22df47bed669089b8150f.svg
        docs/pages/7cbb69a581bc40ca7ad25b29de6d493a2fbcbe45.svg
        docs/pages/b4abcb2f451eb123e3b04b96cbf063ce385957ec.svg
        docs/pages/d8ce6f7453751e8670ed2af67075ca2b3809e49c.mmd
```

Does the final version of either need to be added to the commit? If so, how do we determine which one?

**Comment by iAdramelk** [comment]
> 1. The mermaid charts are working. I'm still getting these errors on refresh, though I'm not sure they're related:

Still can't reproduce it. Tired the same page as in error message, both id dev and prod mode. I'm on Mac with Node.js v16.15.1. Can you please tell me what os and Node version you use?

> 2. Can we make the adjustments required to make it https://github.com/mermaid-js/mermaid/issues/1133?

Plugins itself insert image with `"securityLevel": "loose"` in the config. But the image is not shown on the page right now:

1. For 3rd party images like ``, it shows the image if you access diagram directly, for the plugin itself works. But then you show image on the page linked image return error. My guess is that it is something related to Next's security settings, but it needs additional research and the resulting changes will probably be outside of the plugin.
2. It is more complicated with local images like `../../image.png`. The diagram is generated correctly, but the image itself is not moved to the public location, so it will not work correctly. To make it work, we need to a) parse code block, b) find images and their SRCs, c) move images to public locations, d) update links inside the diagrams. It is possible, but it will take time.

> 3. It looks new files, both svg and mmd are created on every refresh.
>
> Does the final version of either need to be added to the commit? If so, how do we determine which one?

`mmd` file is a tmp file that will be deleted immediately after generating the `svg`. `svg` is only needed to build docs there is no need to commit it. To leave the docs folder clean I added a couple of changes to save images not to the docs folder, but to the `.next/static/assets` - a tmp folder that will be saved between builds. And because of that I also added a check for images in the cache to speed up build time.

**Comment by alexfornuto** [comment]
> 2\. It is more complicated with local images like `../../image.png`. The diagram is generated correctly, but the image itself is not moved to the public location, so it will not work correctly. To make it work, we need to a) parse code block, b) find images and their SRCs, c) move images to public locations, d) update links inside the diagrams. It is possible, but it will take time.

What about assuming (we could spell it out in our Docs reference) that images referenced in mermaid diagrams live in `public/img`? It should only be a small set of icon-type images that we'll want to re-use for diagrams.

I'll test the latest updates and get back to you with answers re: build errors.

**Comment by iAdramelk** [comment]
> > 2. It is more complicated with local images like `../../image.png`. The diagram is generated correctly, but the image itself is not moved to the public location, so it will not work correctly. To make it work, we need to a) parse code block, b) find images and their SRCs, c) move images to public locations, d) update links inside the diagrams. It is possible, but it will take time.
> 
> What about assuming (we could spell it out in our Docs reference) that images referenced in mermaid diagrams live in `public/img`? It should only be a small set of icon-type images that we'll want to re-use for diagrams.
> 
> I'll test the latest updates and get back to you with answers re: build errors.

I did some research. It looks like nested images are disabled in browsers by default, so it will not work even for local ones. See: https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_as_an_Image#restrictions

**Comment by alexfornuto** [comment]
> I did some research. It looks like nested images are disabled in browsers by default, so it will not work even for local ones. See: https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_as_an_Image#restrictions

Would nested images work if the diagrams were rendered client side, as opposed to being statically generated at build? That method may also be desirable if/when we implement a "dark mode" theme for the docs, so that the images can be re-rendered with matching styles.

**Comment by iAdramelk** [comment]
> Would nested images work if the diagrams were rendered client side, as opposed to being statically generated at build? That method may also be desirable if/when we implement a "dark mode" theme for the docs, so that the images can be re-rendered with matching styles.

It depends more not on rendering location but on the way they are inserted on the page. They will not work if we still use image tag, but will work if they are used as an inline svg (run a small manual test just now). Technically we can even inline svg's at the build time, but because mermaid generates random ids every time to prefix css classes we may need to spend some time caching them between page loads.

**Comment by avatus** [comment]
I am also still getting errors on page refresh. I cleared `node_modules` and did a fresh install and it's happening for me. Error importing the static (generated) assets. Error here
```
error - ./content/11.x/docs/pages/index.mdx:21:0
Module not found: Can't resolve '../../../../.next/static/assets/4296ab31c62343945109249f6bd07a5133ae4cd2.svg'
  19 |   title: 'Add your infrastructure'
  20 | }];
> 21 | import _______________next_static_assets_4296ab31c62343945109249f6bd07a5133ae4cd2_svg__ from "../../../../.next/static/assets/4296ab31c62343945109249f6bd07a5133ae4cd2.svg";
  22 | import Layout from "layouts/DocsPage";
  23 | export const meta = {
  24 |   title: 'Introduction to Teleport',

https://nextjs.org/docs/messages/module-not-found
info  - automatically enabled Fast Refresh for 1 custom loader
wait  - compiling /_error (client and server)...
error - ./content/11.x/docs/pages/index.mdx:21:0
Module not found: Can't resolve '../../../../.next/static/assets/4296ab31c62343945109249f6bd07a5133ae4cd2.svg'
  19 |   title: 'Add your infrastructure'
  20 | }];
> 21 | import _______________next_static_assets_4296ab31c62343945109249f6bd07a5133ae4cd2_svg__ from "../../../../.next/static/assets/4296ab31c62343945109249f6bd07a5133ae4cd2.svg";
  22 | import Layout from "layouts/DocsPage";
  23 | export const meta = {
  24 |   title: 'Introduction to Teleport',

```

On page `http://localhost:3000/docs` (index.md from context 11.x)

```
## Try out Teleport
```mermaid
graph LR
    Start --> Stop
```

``` 
Using the snippet above.

**Comment by iAdramelk** [comment]
@avatus, thanks for the report. I'm traveling right now, but I will try to check it on Monday.

**Comment by iAdramelk** [comment]
@avatus status update. I run a bunch of tests locally. I was able to catch this error once, but I haven't found a way to reproduce it after it. Still looking into it.

**Comment by iAdramelk** [comment]
Updated mermaid plugin to work with new hast version. As a side effect problem with non-existing images should be resolved too. (But in a not very beautiful way – we don't have an error anymore because there are no race conditions between updates and rerenders - as we need to manually update the page to see the new image it now has enough time to render).

**Review by avatus — APPROVED** [review]

**Comment by iAdramelk** [comment]
@avatus can I merge it, or do we need additional reviews?

**Comment by avatus** [comment]
I'd wait for one more review 👍

**Comment by alexfornuto** [comment]
Has this been rebased against main since the third version of the hast transformer merged?

**Comment by iAdramelk** [comment]
> Has this been rebased against main since the third version of the hast transformer merged?

@alexfornuto Yep

**Review by alexfornuto — APPROVED** [review]
WHOOO!

**Comment by alexfornuto** [comment]
> It depends more not on rendering location but on the way they are inserted on the page. They will not work if we still use image tag, but will work if they are used as an inline svg (run a small manual test just now). Technically we can even inline svg's at the build time, but because mermaid generates random ids every time to prefix css classes we may need to spend some time caching them between page loads.

Can you provide an example of the syntax needed for this to work?

**Comment by iAdramelk** [comment]
> Can you provide an example of the syntax needed for this to work?

It's more about how the plugin works. Right now plugin creates svg image and saves it to the filesystem. And then inserts it into the page with the `img` tag. E. g. ``.

But with svg it is possible to inline svg files inside the page. E. g. instead of an image tag, write the content of svg file on the page `<svg ...>...</svg>`.

In the case of this plugin, it will mean updating this command https://github.com/gravitational/docs/blob/c2c9d1b5954424272ac1f0d3bf64b9daaa02ab77/server/remark-mermaid.ts#L48-L50 to return the generated string instead of writing it to file. And then creating new hast nodes from the parsed svg string. And then updating class names in the nodes to make them consistent between renders (right now, class names are randomly generated on each render).

**Comment by alexfornuto** [comment]
> to return the generated string instead of writing it to file. And then creating new hast nodes from the parsed svg string. And then updating class names in the nodes to make them consistent between renders (right now, class names are randomly generated on each render).

Well that's thoroughly over my head. I'll save that dream for another day. Thanks!

**Pull request merged**
