### PR TITLE
Update header nav to match main site

### PR DESCRIPTION
**Pull request by PietiKinnunen**
- Updated the navigation to match the new design that's already implemented on https://goteleport.com

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203967393805080

### CODE REVIEW

**Comment by ptgott** [comment]
This works for me! The only issue I have, which may be out of scope for this PR, is that the "Documentation" menu in this PR includes the "Teleport Clients", "How it Works", and "GitHub" items, while the "Documentation" menu on the main site does not. Is this expected?

Also CC @alexfornuto

**Review by alexfornuto — APPROVED** [review]
LGTM! To @ptgott's concern, I think those additional items are slated to be added back to the main site nav.

**Review by alexfornuto — CHANGES_REQUESTED** [review]
Have to rescind my approval, not all the links include the `/docs/` preface.

**Review by alexfornuto — APPROVED** [review]

**Comment by PietiKinnunen** [comment]
@alexfornuto @ptgott I updated the "Learn" link in the "Learn" dropdown to "Guides & Tutorials" as per @ardeche07 request here: https://github.com/gravitational/next/pull/1788#issuecomment-1430178310

**Comment by alexfornuto** [comment]
> @alexfornuto @ptgott I updated the "Learn" link in the "Learn" dropdown to "Guides & Tutorials" as per @ardeche07 request here: [gravitational/next#1788 (comment)](https://github.com/gravitational/next/pull/1788#issuecomment-1430178310)

This was my first time seeing/knowing about this change, and I've brought up a conflict of terminology [on that thread](https://github.com/gravitational/next/pull/1788#issuecomment-1433290157). Maybe hold off until that's sorted.

**Review by alexfornuto — APPROVED** [review]
LGTM from the preview environment.

**Review by TuukkaIkius — APPROVED** [review]
Looks good to me

**Pull request merged**
