### PR TITLE
Lint incorrect messaging in the docs

### LINKED ISSUE #154: Lint MDX files for style
Let's add a linter for some basic docs style rules. We can execute this while running the `yarn markdown-lint` command. The linter would identify incorrect usage and suggest correct alternatives. The goal would be to reduce the number of comments that PR reviewers need to leave and, as as result, the number of review cycles before we can approve a docs change.

Examples of rules we could include:

- Common misuses of Teleport terms, e.g., "auth server" instead of "Auth Service", or mentioning "tsh" outside backticks
- Enforcing a character limit on text in backticks before we require placing the text in a code fence (i.e., using triple-backticks)
- Enforcing a limit on words in a paragraph (e.g., 50 words)
- Using sentence case for headings (if this is possible)

### PR DESCRIPTION
**Pull request by ptgott**
Closes #154

One challenge for maintaining the docs is ensuring that we maintain consistent terms for different Teleport products and components.

This change adds a linter to prevent incorrect usage of terms and suggest alternatives with an explanation.

The configuration file, which must live in `docs/messaging-config.json` within a `gravitational/teleport` repo, looks like this, an array where each element is an object that specifies a rule:

```json
[
    {
    	"incorrect": "\\W(machine id|(database|app(lication)?|desktop|kubernetes|ssh|discovery) service)\\W",
    	"correct": "capitalize the names of Teleport services",
    	"explanation": "We want to ensure that product names are consistent across the docs"
    }
]
```

The `incorrect` field is a regular expression indicating a pattern to avoid. The config above would show a warning in the linter on, for example, `machine id`, `database service`, and `app service`. The `correct` and `explanation` fields are used to print error messages.

The intention is for docs authors to be able to adjust the linter config along with the docs content.

### CODE REVIEW

**Review by avatus — APPROVED** [review]

**Comment by hatched** [comment]
Are you sure we want the configuration values to live within the `teleport` repo itself and not be defined globally for the documentation?

**Comment by ptgott** [comment]
@hatched I went back and forth on this one. 

I opted for loading the config from `gravitational/teleport` so docs authors could propose changes to the config at the same time as changes to the docs, e.g., to remove an outdated term while also preventing future occurrences of the term from making it into the docs.

At the same time, I'm not sure if there's ever a situation where we want our messaging rules to differ from version to version of the docs. For example, when we moved away from using "Server Access", "Kubernetes Access", etc., it's not like we only started using the new messaging with a particular release. 

I'm happy to change this to load the config from `gravitational/docs` and see if authors run into friction—it makes sense to have messaging rules for all versions, and if there are issues later on, we can always think about having both global rules (in `gravitational/docs`) and version-specific ones (in `gravitational/teleport`).

**Comment by ptgott** [comment]
@hatched I've pushed a change that loads the config from `gravitational/docs`. This also includes a config.

@alexfornuto Does [the config](https://github.com/gravitational/docs/blob/edf8f65dc4af54e62fa3ad175445a7c030c4e98c/messaging-config.json) look okay to you? It includes rules for:

- Capitalizing service names
- Not saying "auth and proxy"
- Not saying "<Resource> Access"

**Review by hatched — APPROVED** [review]
Looks good! Thanks for the updates.

**Review by alexfornuto — APPROVED** [review]

**Comment by ptgott** [comment]
## To do before merging:

Merge fixes in `gravitational/teleport` for:

- [ ]`master` (have a branch up)
- [ ] Merge fixes for v12 (need to backport from `master)
- [ ] Merge fixes for v11 (need to backport from `master)
- [ ] Merge fixes for v10 (need to backport from `master)

**Comment by ptgott** [comment]
@hatched After attempting to apply fixes (https://github.com/gravitational/teleport/pull/22270), it turned out that replacing "<Service> Access" in titles was pretty awkward. I implemented the ability to only apply the messaging rules to certain parts of the docs, e.g., ignoring the title. This also allows us to be clearer in warning messages re: where an error took place.

**Review by avatus — APPROVED** [review]

**Comment by ptgott** [comment]
@avatus I rebased this on top of the docs re-architecting so it wouldn't cause OOMs when deploying. Would you have time for another review? Thanks!

**Review by avatus — APPROVED** [review]

**Pull request merged**
