### PR TITLE
Docs: 404 page update

### PR DESCRIPTION
**Pull request by mmcallister**
This is for issue https://github.com/gravitational/docs/issues/188

The 404 page in Docs needs some work.

Docs
https://goteleport.com/docs/blah/

vs

Website
https://goteleport.com/blah/

### CODE REVIEW

**Comment by avatus** [comment]
This looks like a bunch of extra commits got dragged in on accident. Could you take a look?

**Review by benarent — COMMENTED** [review]
also a lot of conflicts, can you fix those first

**Comment by mmcallister** [comment]
@travelton when you have bandwidth can you have a look too? The commits look relevant and the conflicts minor, as this issue has been open for awhile.

**Comment by avatus** [comment]
I think a bunch of extra commits got dragged into this one on accident. can you rebase on main and squash the 404 changes and see if that fixes it? thanks

**Comment by travelton** [comment]
Not sure what happened here. Rather than rebasing and force pushing, let's abandon this PR and start with a clean slate. See https://github.com/gravitational/docs/pull/501

**Pull request closed without merging**
